jobs = [
    {
        "id": 1,
        "title": "ReactJS Developer",
        "location": "Surat",
        "salary": "$25K–$30K annually",
        "experience": "3 Years",
        "type": "Full Time",
        "mode": "On Site",
        "company": "Brooklyn",
        "candidates_applied": 15,
        "completed_interviews": 8,
        "match_percentage": 90,
        "status": "open",
        "posted_days_ago": 3,
        "posted_date": (2026, 1, 18),
        "work_type": "Presencial",
        "tiempo": "3 días atrás",
        "total_positions": 3,
        "proceso": "En entrevista",
        "job_description": "Develop and maintain modern React web applications with high performance and scalability.",
        "responsibilities": [
            "Build reusable React components",
            "Optimize UI performance",
            "Collaborate with backend teams",
            "Write clean and maintainable code",
            "Participate in code reviews"
        ],
        "requirements": [
            "3+ years experience with ReactJS",
            "Strong JavaScript and ES6+ knowledge",
            "Experience working with REST APIs",
            "Familiarity with Git",
            "Good problem-solving skills"
        ]
    },
    {
        "id": 2,
        "title": "Python Developer",
        "location": "Mumbai",
        "salary": "$30K–$40K annually",
        "experience": "2 Years",
        "type": "Full Time",
        "mode": "Remote",
        "company": "TechSoft",
        "candidates_applied": 20,
        "completed_interviews": 10,
        "match_percentage": 85,
        "status": "closed",
        "posted_days_ago": 10,
        "posted_date": (2026, 1, 11),
        "work_type": "Remoto",
        "tiempo": "10 días atrás",
        "total_positions": 1,
        "proceso": "Descartado",
        "job_description": "Build backend services, APIs, and automation tools using Python.",
        "responsibilities": [
            "Develop REST APIs",
            "Maintain backend systems",
            "Optimize database queries",
            "Write unit tests",
            "Fix production issues"
        ],
        "requirements": [
            "2+ years Python experience",
            "Flask or Django knowledge",
            "SQL databases experience",
            "Understanding of REST APIs",
            "Linux basics"
        ]
    },
    {
        "id": 3,
        "title": "NodeJS Developer",
        "location": "Delhi",
        "salary": "$28K–$35K annually",
        "experience": "3 Years",
        "type": "Contract",
        "mode": "Hybrid",
        "company": "CodeLab",
        "candidates_applied": 12,
        "completed_interviews": 5,
        "match_percentage": 78,
        "status": "open",
        "posted_days_ago": 5,
        "posted_date": (2026, 1, 16),
        "work_type": "Híbrido",
        "tiempo": "5 días atrás",
        "total_positions": 6,
        "proceso": "Ofertas",
        "job_description": "Develop scalable backend services and APIs using NodeJS.",
        "responsibilities": [
            "Create REST APIs",
            "Integrate databases",
            "Improve performance",
            "Maintain server security",
            "Deploy applications"
        ],
        "requirements": [
            "NodeJS experience",
            "MongoDB or PostgreSQL",
            "API development knowledge",
            "Docker basics",
            "Problem solving skills"
        ]
    },
    {
        "id": 4,
        "title": "Frontend Developer",
        "location": "Ahmedabad",
        "salary": "$22K–$28K annually",
        "experience": "1 Year",
        "type": "Full Time",
        "mode": "On Site",
        "company": "WebWorks",
        "candidates_applied": 18,
        "completed_interviews": 9,
        "match_percentage": 88,
        "status": "open",
        "posted_days_ago": 7,
        "posted_date": (2026, 1, 14),
        "work_type": "Presencial",
        "tiempo": "7 días atrás",
        "total_positions": 5,
        "proceso": "Descartado",
        "job_description": "Design and build responsive user interfaces.",
        "responsibilities": [
            "Create UI components",
            "Maintain CSS styles",
            "Optimize UX",
            "Fix layout issues",
            "Collaborate with designers"
        ],
        "requirements": [
            "HTML/CSS/JS knowledge",
            "React basics",
            "Responsive design",
            "Git usage",
            "Attention to detail"
        ]
    },
    {
        "id": 5,
        "title": "Backend Developer",
        "location": "Pune",
        "salary": "$35K–$45K annually",
        "experience": "4 Years",
        "type": "Full Time",
        "mode": "Remote",
        "company": "DataStack",
        "candidates_applied": 25,
        "completed_interviews": 12,
        "match_percentage": 92,
        "status": "closed",
        "posted_days_ago": 15,
        "posted_date": (2026, 1, 6),
        "work_type": "Remoto",
        "tiempo": "15 días atrás",
        "total_positions": 4,
        "proceso": "Descartado",
        "job_description": "Build secure and scalable backend systems.",
        "responsibilities": [
            "API development",
            "Database optimization",
            "System monitoring",
            "Security implementation",
            "Cloud deployment"
        ],
        "requirements": [
            "Backend frameworks experience",
            "Database management",
            "Cloud services",
            "Docker",
            "System design knowledge"
        ]
    },
    {
        "id": 6,
        "title": "Mobile App Developer",
        "location": "Bangalore",
        "salary": "$40K–$50K annually",
        "experience": "5 Years",
        "type": "Full Time",
        "mode": "Hybrid",
        "company": "AppZone",
        "candidates_applied": 30,
        "completed_interviews": 15,
        "match_percentage": 95,
        "status": "open",
        "posted_days_ago": 1,
        "posted_date": (2026, 1, 20),
        "work_type": "Híbrido",
        "tiempo": "1 día atrás",
        "total_positions": 2,
        "proceso": "Aceptado",
        "job_description": "Develop cross-platform mobile applications.",
        "responsibilities": [
            "Build mobile UI",
            "Integrate APIs",
            "Optimize performance",
            "Publish apps",
            "Fix bugs"
        ],
        "requirements": [
            "Flutter or React Native",
            "API integration",
            "Mobile UI skills",
            "App store experience",
            "Debugging skills"
        ]
    },
    {
        "id": 7,
        "title": "UI/UX Designer",
        "location": "Chennai",
        "salary": "$20K–$27K annually",
        "experience": "2 Years",
        "type": "Part Time",
        "mode": "Remote",
        "company": "DesignHub",
        "candidates_applied": 14,
        "completed_interviews": 6,
        "match_percentage": 80,
        "status": "closed",
        "posted_days_ago": 12,
        "posted_date": (2026, 1, 9),
        "work_type": "Remoto",
        "tiempo": "12 días atrás",
        "total_positions": 1,
        "proceso": "Descartado",
        "job_description": "Design intuitive user interfaces and experiences.",
        "responsibilities": [
            "Create wireframes",
            "Design prototypes",
            "User research",
            "Collaborate with developers",
            "Improve usability"
        ],
        "requirements": [
            "Figma or Adobe XD",
            "UX principles",
            "Portfolio required",
            "Creativity",
            "Communication skills"
        ]
    },
    {
        "id": 8,
        "title": "DevOps Engineer",
        "location": "Hyderabad",
        "salary": "$45K–$60K annually",
        "experience": "5 Years",
        "type": "Full Time",
        "mode": "On Site",
        "company": "CloudNet",
        "candidates_applied": 10,
        "completed_interviews": 4,
        "match_percentage": 89,
        "status": "open",
        "posted_days_ago": 8,
        "posted_date": (2026, 1, 15),
        "work_type": "Presencial",
        "tiempo": "8 días atrás",
        "total_positions": 2,
        "proceso": "En entrevista",
        "job_description": "Maintain CI/CD pipelines and cloud infrastructure.",
        "responsibilities": [
            "Automate deployments",
            "Monitor servers",
            "Improve reliability",
            "Manage cloud services",
            "Security compliance"
        ],
        "requirements": [
            "AWS or Azure",
            "Docker & Kubernetes",
            "Linux",
            "CI/CD pipelines",
            "Monitoring tools"
        ]
    },
    {
        "id": 9,
        "title": "Data Analyst",
        "location": "Kolkata",
        "salary": "$32K–$38K annually",
        "experience": "3 Years",
        "type": "Contract",
        "mode": "Remote",
        "company": "InsightAI",
        "candidates_applied": 22,
        "completed_interviews": 11,
        "match_percentage": 87,
        "status": "closed",
        "posted_days_ago": 20,
        "posted_date": (2026, 1, 3),
        "work_type": "Remoto",
        "tiempo": "20 días atrás",
        "total_positions": 4,
        "proceso": "Descartado",
        "job_description": "Analyze data and generate business insights.",
        "responsibilities": [
            "Create dashboards",
            "Analyze datasets",
            "Generate reports",
            "Data cleaning",
            "Present findings"
        ],
        "requirements": [
            "SQL",
            "Python or R",
            "Power BI / Tableau",
            "Statistics",
            "Critical thinking"
        ]
    },
    {
        "id": 10,
        "title": "QA Engineer",
        "location": "Jaipur",
        "salary": "$18K–$25K annually",
        "experience": "1 Year",
        "type": "Full Time",
        "mode": "On Site",
        "company": "TestPro",
        "candidates_applied": 16,
        "completed_interviews": 7,
        "match_percentage": 82,
        "status": "open",
        "posted_days_ago": 4,
        "posted_date": (2026, 1, 17),
        "work_type": "Presencial",
        "tiempo": "4 días atrás",
        "total_positions": 3,
        "proceso": "Descartado",
        "job_description": "Ensure software quality through testing and automation.",
        "responsibilities": [
            "Write test cases",
            "Manual testing",
            "Automation scripts",
            "Bug reporting",
            "Regression testing"
        ],
        "requirements": [
            "QA fundamentals",
            "Automation basics",
            "Attention to detail",
            "Documentation skills",
            "Team collaboration"
        ]
    }
]
