"""create postulations table

Revision ID: 58ba8c815037
Revises: d022bd80fc01
Create Date: 2026-01-21 18:10:06.422841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ba8c815037'
down_revision = 'd022bd80fc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('postulation_state', sa.String(
                        length=50), nullable=False),
                    sa.Column('company_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('role', sa.String(length=100), nullable=False),
                    sa.Column('experience', sa.Integer(), nullable=False),
                    sa.Column('inscription_date', sa.Date(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('salary', sa.Integer(), nullable=False),
                    sa.Column('platform', sa.String(
                        length=100), nullable=False),
                    sa.Column('postulation_url', sa.String(
                        length=2000), nullable=False),
                    sa.Column('work_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('requirements', sa.JSON(), nullable=False),
                    sa.Column('candidates_applied',
                              sa.Integer(), nullable=False),
                    sa.Column('available_positions',
                              sa.Integer(), nullable=False),
                    sa.Column('job_description', sa.String(
                        length=500), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
                    )
    op.create_table('profile',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('image_filename', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=True),
                    sa.Column('bio', sa.VARCHAR(length=5000),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('gender_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['gender_id'], ['gender.id'], name=op.f('profile_gender_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], name=op.f('profile_user_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('profile_pkey'))
                    )
    op.create_table('postulaciones_skill',
                    sa.Column('postulaciones_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('skill_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['postulaciones_id'], ['postulaciones.id'], name=op.f(
                        'postulaciones_skill_postulaciones_id_fkey')),
                    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f(
                        'postulaciones_skill_skill_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'postulaciones_id', 'skill_id', name=op.f('postulaciones_skill_pkey'))
                    )
    op.create_table('postulaciones',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('nombre_empressa', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('persona_de_contacto', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email_de_contacto', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('city_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('social_media_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('status_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('category_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('work_type_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('employment_type_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f(
                        'postulaciones_category_id_fkey')),
                    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f(
                        'postulaciones_city_id_fkey')),
                    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_type.id'], name=op.f(
                        'postulaciones_employment_type_id_fkey')),
                    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.id'], name=op.f(
                        'postulaciones_social_media_id_fkey')),
                    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f(
                        'postulaciones_status_id_fkey')),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f(
                        'postulaciones_user_id_fkey')),
                    sa.ForeignKeyConstraint(['work_type_id'], ['work_type.id'], name=op.f(
                        'postulaciones_work_type_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('postulaciones_pkey'))
                    )
    op.create_table('profile_skill',
                    sa.Column('profile_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('skill_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f(
                        'profile_skill_profile_id_fkey')),
                    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f(
                        'profile_skill_skill_id_fkey')),
                    sa.PrimaryKeyConstraint('profile_id', 'skill_id',
                                            name=op.f('profile_skill_pkey'))
                    )
    op.create_table('gender',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('gender_pkey'))
                    )
    op.create_table('employment_type',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('employment_type_pkey'))
                    )
    op.create_table('category',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
                    )
    op.create_table('social_media',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('image_filename', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('social_media_pkey'))
                    )
    op.create_table('work_type',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('work_type_pkey'))
                    )
    op.create_table('city',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('city_pkey'))
                    )
    op.create_table('status',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('status_pkey'))
                    )
    op.drop_table('postulations')
    # ### end Alembic commands ###
