"""empty message

Revision ID: 8ffff034d283
Revises: 73aab1002b92
Create Date: 2026-01-22 12:20:52.116890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffff034d283'
down_revision = '73aab1002b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_company', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('candidatos', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulaciones')
    # ### end Alembic commands ###
