"""empty message

Revision ID: a26349e7efa7
Revises: 8ffff034d283
Create Date: 2026-01-22 14:04:59.782254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26349e7efa7'
down_revision = '8ffff034d283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reqerments', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.drop_column('reqerments')

    # ### end Alembic commands ###
