"""empty message

Revision ID: d6e4689207ab
Revises: e07aa83b37ea
Create Date: 2026-01-19 22:48:08.627892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e4689207ab'
down_revision = 'e07aa83b37ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_postulacion_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'postulaciones', ['postulacion_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_postulacion_id_fkey'), 'postulaciones', ['postulacion_id'], ['id'])

    # ### end Alembic commands ###
