"""empty message

Revision ID: e0307d4f785d
Revises: cf810a939ea9
Create Date: 2026-01-19 22:13:20.238432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0307d4f785d'
down_revision = 'cf810a939ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.alter_column('social_media_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.alter_column('social_media_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
