"""empty message

Revision ID: e07aa83b37ea
Revises: 48cfd1d3085e
Create Date: 2026-01-19 22:37:30.963860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07aa83b37ea'
down_revision = '48cfd1d3085e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.alter_column('social_media_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.alter_column('social_media_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
